const fruits = {
  collection: 'fruits',
  'base-path': './assets/collections/fruits',
  size: {
    height: 512,
    width: 512,
  },
  tags: ['price', 'fruit', 'food'],
  assets: {
    '001-melon': {
      assetName: '001-melon.svg',
      name: 'melon',
      dollar_price: '$13.73',
      won_price: '₩19,986',
    },
    '002-pomegranate': {
      assetName: '002-pomegranate.svg',
      name: 'pomegranate',
      dollar_price: '$10.74',
      won_price: '₩19,728',
    },
    '003-orange': {
      assetName: '003-orange.svg',
      name: 'orange',
      dollar_price: '$7.37',
      won_price: '₩11,351',
    },
    '004-apple': {
      assetName: '004-apple.svg',
      name: 'apple',
      dollar_price: '$11.59',
      won_price: '₩15,120',
    },
    '005-pumpkin': {
      assetName: '005-pumpkin.svg',
      name: 'pumpkin',
      dollar_price: '$7.44',
      won_price: '₩17,975',
    },
    '006-tangerine': {
      assetName: '006-tangerine.svg',
      name: 'tangerine',
      dollar_price: '$3.63',
      won_price: '₩14,343',
    },
    '007-cherry': {
      assetName: '007-cherry.svg',
      name: 'cherry',
      dollar_price: '$12.26',
      won_price: '₩10,245',
    },
    '008-banana': {
      assetName: '008-banana.svg',
      name: 'banana',
      dollar_price: '$4.96',
      won_price: '₩18,844',
    },
    '009-avocado': {
      assetName: '009-avocado.svg',
      name: 'avocado',
      dollar_price: '$15.45',
      won_price: '₩18,076',
    },
    '010-apricot': {
      assetName: '010-apricot.svg',
      name: 'apricot',
      dollar_price: '$2.97',
      won_price: '₩16,636',
    },
    '011-peach': {
      assetName: '011-peach.svg',
      name: 'peach',
      dollar_price: '$3.24',
      won_price: '₩13,998',
    },
    '012-pineapple': {
      assetName: '012-pineapple.svg',
      name: 'pineapple',
      dollar_price: '$3.20',
      won_price: '₩12,721',
    },
    '013-grapes': {
      assetName: '013-grapes.svg',
      name: 'grapes',
      dollar_price: '$6.88',
      won_price: '₩12,806',
    },
    '014-pear': {
      assetName: '014-pear.svg',
      name: 'pear',
      dollar_price: '$14.69',
      won_price: '₩14,895',
    },
    '015-watermelon': {
      assetName: '015-watermelon.svg',
      name: 'watermelon',
      dollar_price: '$12.57',
      won_price: '₩9,797',
    },
    '016-mango': {
      assetName: '016-mango.svg',
      name: 'mango',
      dollar_price: '$10.31',
      won_price: '₩18,957',
    },
    '017-kiwi': {
      assetName: '017-kiwi.svg',
      name: 'kiwi',
      dollar_price: '$6.47',
      won_price: '₩9,444',
    },
    '018-plum': {
      assetName: '018-plum.svg',
      name: 'plum',
      dollar_price: '$15.64',
      won_price: '₩15,629',
    },
    '019-strawberry': {
      assetName: '019-strawberry.svg',
      name: 'strawberry',
      dollar_price: '$14.24',
      won_price: '₩7,032',
    },
    '020-Raspberry': {
      assetName: '020-Raspberry.svg',
      name: 'Raspberry',
      dollar_price: '$8.89',
      won_price: '₩11,245',
    },
    '021-cranberry': {
      assetName: '021-cranberry.svg',
      name: 'cranberry',
      dollar_price: '$4.72',
      won_price: '₩11,213',
    },
    '022-blueberry': {
      assetName: '022-blueberry.svg',
      name: 'blueberry',
      dollar_price: '$10.41',
      won_price: '₩16,964',
    },
    '023-coconut': {
      assetName: '023-coconut.svg',
      name: 'coconut',
      dollar_price: '$2.12',
      won_price: '₩17,138',
    },
    '024-figs': {
      assetName: '024-figs.svg',
      name: 'figs',
      dollar_price: '$13.08',
      won_price: '₩19,050',
    },
    '025-grapefruit': {
      assetName: '025-grapefruit.svg',
      name: 'grapefruit',
      dollar_price: '$12.85',
      won_price: '₩19,306',
    },
    '026-dragon fruit': {
      assetName: '026-dragon fruit.svg',
      name: 'dragon fruit',
      dollar_price: '$10.46',
      won_price: '₩13,908',
    },
    '027-papaya': {
      assetName: '027-papaya.svg',
      name: 'papaya',
      dollar_price: '$8.54',
      won_price: '₩16,385',
    },
    '028-guava': {
      assetName: '028-guava.svg',
      name: 'guava',
      dollar_price: '$12.92',
      won_price: '₩19,370',
    },
    '029-Lychee': {
      assetName: '029-Lychee.svg',
      name: 'Lychee',
      dollar_price: '$15.02',
      won_price: '₩13,368',
    },
    '030-passion fruit': {
      assetName: '030-passion fruit.svg',
      name: 'passion fruit',
      dollar_price: '$8.64',
      won_price: '₩10,303',
    },
    '031-lime': {
      assetName: '031-lime.svg',
      name: 'lime',
      dollar_price: '$13.53',
      won_price: '₩17,150',
    },
    '032-sapodilla': {
      assetName: '032-sapodilla.svg',
      name: 'sapodilla',
      dollar_price: '$14.90',
      won_price: '₩12,482',
    },
    '033-longan': {
      assetName: '033-longan.svg',
      name: 'longan',
      dollar_price: '$10.07',
      won_price: '₩8,055',
    },
    '034-olive': {
      assetName: '034-olive.svg',
      name: 'olive',
      dollar_price: '$12.36',
      won_price: '₩9,246',
    },
    '035-cantaloupe': {
      assetName: '035-cantaloupe.svg',
      name: 'cantaloupe',
      dollar_price: '$5.69',
      won_price: '₩12,273',
    },
    '036-dates': {
      assetName: '036-dates.svg',
      name: 'dates',
      dollar_price: '$12.81',
      won_price: '₩18,981',
    },
    '037-loquat': {
      assetName: '037-loquat.svg',
      name: 'loquat',
      dollar_price: '$8.08',
      won_price: '₩18,772',
    },
    '038-permission': {
      assetName: '038-permission.svg',
      name: 'permission',
      dollar_price: '$14.48',
      won_price: '₩8,931',
    },
    '039-sapodilla': {
      assetName: '039-sapodilla.svg',
      name: 'sapodilla',
      dollar_price: '$3.16',
      won_price: '₩11,284',
    },
    '040-custard apple': {
      assetName: '040-custard apple.svg',
      name: 'custard apple',
      dollar_price: '$12.03',
      won_price: '₩9,925',
    },
    '041-carambola': {
      assetName: '041-carambola.svg',
      name: 'carambola',
      dollar_price: '$5.68',
      won_price: '₩13,762',
    },
    '042-quince': {
      assetName: '042-quince.svg',
      name: 'quince',
      dollar_price: '$6.82',
      won_price: '₩18,062',
    },
    '043-ch': {
      assetName: '043-ch.svg',
      name: 'ch',
      dollar_price: '$12.38',
      won_price: '₩6,469',
    },
    '044-currant': {
      assetName: '044-currant.svg',
      name: 'currant',
      dollar_price: '$10.45',
      won_price: '₩13,839',
    },
    '045-cashew': {
      assetName: '045-cashew.svg',
      name: 'cashew',
      dollar_price: '$6.92',
      won_price: '₩14,601',
    },
  },
};

export default fruits;
